<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>
		Copyright (C) 2013 - 2014 Peter Varo
		&lt;http://github.com/petervaro/python&gt;
		Copyright (C) 2016 Evan Hubinger
		&lt;http://github.com/evhub/sublime-coconut&gt;

		This program is free software: you can redistribute it
		and/or modify it under the terms of the GNU General
		Public License as published by the Free Software
		Foundation, either version 3 of the License, or (at your
		option) any later version.

		This program is distributed in the hope that it will be
		useful, but WITHOUT ANY WARRANTY; without even the
		implied warranty of MERCHANTABILITY or FITNESS FOR A
		PARTICULAR PURPOSE. See the GNU General Public License
		for more details.

		You should have received a copy of the GNU General Public
		License along with this program, most likely a file in
		the root directory, called "LICENSE". If not, see
		&lt;http://www.gnu.org/licenses&gt;.
	</string>
	<key>fileTypes</key>
	<array>
		<string>coc</string>
		<string>coco</string>
		<string>coconut</string>
		<string>py_template</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!/.*\bcoconut[\d.-]*\b</string>
	<key>foldingStartMarker</key>
	<string>^\s*(def|class|(?&lt;!\\)data)\s+([.\w&gt;]+)\s*(\((.*)\))?\s*:|\{\s*$|\(\s*$|\[\s*$|^\s*"""(?=.)(?!.*""")</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)|^\s*"""\s*$</string>
	<key>keyEquivalent</key>
	<string>^~O</string>
	<key>name</key>
	<string>Coconut</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0b[01_]+</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0x[\h_]+</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0o[0-7_]+</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)(?&lt;=\W|^)\.\d[\d_]*([eE][+-]?\d[\d_]*)?[iIjJ]?(?!\.)</string>
			<key>name</key>
			<string>constant.numeric.float_and_complex.decimal.floatnumber.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d[\d_]*\.([\d_]*([eE][+-]?\d[\d_]*)?)?[iIjJ]?(?=\W)(?!\.)</string>
			<key>name</key>
			<string>constant.numeric.float_and_complex.decimal.pointfloat.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![\.\d_])\d[\d_]*[eE][+-]?\d[\d_]*[iIjJ]?</string>
			<key>name</key>
			<string>constant.numeric.float_and_complex.decimal.exponent.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!\.)([1-9][\d_]*|0)[iIjJ]?</string>
			<key>name</key>
			<string>constant.numeric.integer_and_complex.decimal.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(global|nonlocal)\b</string>
			<key>name</key>
			<string>storage.modifier.declaration.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(async|await)\b</string>
			<key>name</key>
			<string>storage.modifier.coroutine.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(import|from)\b</string>
			<key>name</key>
			<string>keyword.control.import_and_import_from.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(elif|else|except|finally|for|if|try|while|with|break|continue|pass|raise|return|yield|(?&lt;!\\)(match|case|where))\b</string>
			<key>name</key>
			<string>keyword.control.flow_block_delimiters.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|in|is|not|or)\b</string>
			<key>name</key>
			<string>keyword.operator.bool.logical.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(as|assert|del|\?)\b</string>
			<key>name</key>
			<string>keyword.other.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;=|&gt;=|==|&lt;(?!\*|\|)|&gt;|!=|≠|≤|≥|¬=</string>
			<key>name</key>
			<string>keyword.operator.comparison.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\+|-|\*|\*\*|/|//|%|&lt;&lt;|&gt;&gt;|&amp;|\^|~|@|::|\$|\|\??\*?\*?&gt;|&lt;\*?\*?\||`|&lt;?\*?\*?\.\.\*?\*?&gt;?|\?\??|\|→|\??\*?\*?↦|↤\*?\*?|&lt;?\*?∘\*?&gt;?|⋅|↑|÷|−|⁻|∧|∩|∨|∪|⊻|⊕|«|»|×|…)=</string>
			<key>name</key>
			<string>keyword.operator.assignment.augmented.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\*|\*\*|/|//|%|&lt;&lt;|&gt;&gt;|&amp;|\^|~|@|::|\$|\|\??\*?\*?&gt;|&lt;\*?\*?\||`|&lt;?\*?\*?\.\.(?!\.)\*?\*?&gt;?|\?\??|\|→|\??\*?\*?↦|↤\*?\*?|&lt;?\*?∘\*?&gt;?|⋅|↑|÷|−|⁻|¬|∧|∩|∨|∪|⊻|⊕|«|»|×|…</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=|-&gt;</string>
			<key>name</key>
			<string>keyword.operator.value_and_annotation_assignment.coconut</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(class|(?&lt;!\\)data)\s+(?=[a-zA-Z_]\w*(\s*\()?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)?([ \t\r\f\v]+\w+)?[ \t\r\f\v]*(?:\n|:|(?=#))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.coconut</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#class_entity_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class_inheritance</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*((?:match|addpattern)\s+)?(async\s+)?((?:match|addpattern)\s+)?(def)\s+(?=[a-zA-Z_][\w.]*\s*\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.coconut</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.coroutine.coconut</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.coconut</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(:|=)</string>
			<key>endCaptures</key>
			<dict/>
			<key>name</key>
			<string>meta.function.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_entity_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_arguments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_annotation</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(lambda)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.anonymous.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>:</string>
			<key>name</key>
			<string>meta.function.anonymous.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s+</string>
					<key>end</key>
					<string>(?=:)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\b([a-zA-Z_]\w*)\s*(=)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.function.coconut</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.coconut</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=,|:)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\b[a-zA-Z_]\w*</string>
							<key>name</key>
							<string>variable.parameter.function.coconut</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>@</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(None|True|False|Ellipsis|NotImplemented|TYPE_CHECKING)\b</string>
			<key>name</key>
			<string>constant.language.word_like.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\W|^)\.\.\.(?=\W|$)</string>
			<key>name</key>
			<string>constant.language.symbol_like.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(def|lambda)\b</string>
			<key>name</key>
			<string>storage.type.function.coconut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(class|(?&lt;!\\)data)\b</string>
			<key>name</key>
			<string>storage.type.class.coconut</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin_types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin_functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin_exceptions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#magic_function_names</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#magic_variable_names</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#language_variables</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.structure.list.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\[|,)\s*(?![\],])</string>
					<key>end</key>
					<string>\s*(?:,|(?=\]))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.structure.dictionary.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\{|,|^)\s*(?![,}])</string>
					<key>end</key>
					<string>\s*(?:(?=\})|:)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=:|^)\s*</string>
					<key>end</key>
					<string>\s*(?:(?=\})|,)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=,|;|=|\+|-|\*|/|\||:|&lt;|&gt;|~|%|\^|\\|@|`|\\)\s*\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.structure.group.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!:|,|;|\[|\{|\}|=|\+|-|\*|/|\||&lt;|&gt;|~|%|\^|\\|\n|@|`|\\)\s*\$?\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.function_call.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_arguments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#f_string_quoted</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_regex</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>builtin_exceptions</key>
		<dict>
			<key>match</key>
			<string>\b((Arithmetic|Buffer|Lookup|Assertion|Attribute|EOF|FloatingPoint|Import|Index|Key|Memory|Name|NotImplemented|OS|Overflow|Reference|Runtime|Syntax|Indentation|Tab|System|Type|UnboundLocal|Unicode(Encode|Decode|Translate)?|Value|ZeroDivision|Environment|IO|VMS|Windows|BlockingIO|ChildProcess|BrokenPipe|Connection(Aborted|Refused|Reset)?|FileExists|FileNotFound|Interrupted|(Is|Not)ADirectory|Permission|ProcessLookup|Timeout)Error|(User|Deprecation|PendingDeprecation|Syntax|Runtime|Future|Import|Bytes|Resource)Warning|(Base)?Exception|(Generator|System)Exit|KeyboardInterrupt|Stop(Async)?Iteration|Warning|MatchError)\b</string>
			<key>name</key>
			<string>support.type.exception.coconut</string>
		</dict>
		<key>builtin_functions</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!(?&lt;!\.)\.)\b(__import__|abs|all|any|ascii|bin|callable|(py_)?chr|compile|delattr|dir|divmod|eval|exec|(py_)?filter|format|getattr|globals|hasattr|hash|help|(py_)?hex|id|(py_)?input|isinstance|issubclass|iter|len|locals|vars|min|next|oct|ord|pow|(py_)?print|repr|round|setattr|sorted|sum|max|reduce|takewhile|dropwhile|tee|makedata|consume|py_raw_input|py_xrange|addpattern|recursive_iterator|reiterable|scan|groupsof|memoize|fmap|(py_)?breakpoint)\b</string>
			<key>name</key>
			<string>support.function.builtin.coconut</string>
		</dict>
		<key>builtin_types</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!(?&lt;!\.)\.)\b(bool|bytearray|bytes|classmethod|complex|dict|(py_)?range|tuple|(py_)?enumerate|float|frozenset|(py_)?int|list|memoryview|(py_)?object|(py_)?open|property|(py_)?reversed|set|slice|staticmethod|(py_)?str|super|type|(py_)?map|(py_)?zip|parallel_map|count|concurrent_map|starmap|zip_longest)\b</string>
			<key>name</key>
			<string>support.type.coconut</string>
		</dict>
		<key>class_entity_name</key>
		<dict>
			<key>begin</key>
			<string>(?=[a-zA-Z_]\w*)</string>
			<key>contentName</key>
			<string>entity.name.type.class.coconut</string>
			<key>end</key>
			<string>(?!\w)\s*(\bfrom\b)?</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.coconut</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entity_name_class</string>
				</dict>
			</array>
		</dict>
		<key>class_inheritance</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>contentName</key>
			<string>meta.class.inheritance.coconut</string>
			<key>end</key>
			<string>\)(\s*\bfrom\b)?|\s*(?=:|\n)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.coconut</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\(|,)\s*</string>
					<key>contentName</key>
					<string>entity.other.inherited-class.coconut</string>
					<key>end</key>
					<string>\s*(?:,|(?=\)))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.inheritance.coconut</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_extended_re</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_extended_old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_extended_fmt</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_extended_tmp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#.*$\n?</string>
					<key>name</key>
					<string>comment.line.hashmark.coconut</string>
				</dict>
			</array>
		</dict>
		<key>comment_extended_fmt</key>
		<dict>
			<key>begin</key>
			<string>(?i)(#(#|\s)*syntax:fmt)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.hashmark.extended.fmt.open.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)(#(#|\s)*end:fmt)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.hashmark.extended.fmt.close.coconut</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.syntax.comment.line.hashmark.extended.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_quoted_format</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>comment_extended_old</key>
		<dict>
			<key>begin</key>
			<string>(?i)(#(#|\s)*syntax:old)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.hashmark.extended.fmt.open.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)(#(#|\s)*end:old)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.hashmark.extended.fmt.close.coconut</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.syntax.comment.line.hashmark.extended.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_quoted_old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>comment_extended_re</key>
		<dict>
			<key>begin</key>
			<string>(?i)(#(#|\s)*syntax:re)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.hashmark.extended.re.open.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)(#(#|\s)*end:re)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.hashmark.extended.re.close.coconut</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.syntax.comment.line.hashmark.extended.re.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_quoted_regex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>comment_extended_tmp</key>
		<dict>
			<key>begin</key>
			<string>(?i)(#(#|\s)*syntax:tmp)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.hashmark.extended.tmp.open.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)(#(#|\s)*end:tmp)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.hashmark.extended.tmp.close.coconut</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.syntax.comment.line.hashmark.extended.tmp.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_quoted_template</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>constant_placeholder</key>
		<dict>
			<key>match</key>
			<string>%(\(\w+\))?#?0?-?[ ]?\+?(\d*|\*)(\.(\d*|\*))?[hlL]?[diouxXeEfFgGcrs%]</string>
			<key>name</key>
			<string>string.interpolated.placeholder.coconut</string>
		</dict>
		<key>entity_name_class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#illegal_names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generic_names</string>
				</dict>
			</array>
		</dict>
		<key>entity_name_function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#magic_function_names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal_names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generic_names</string>
				</dict>
			</array>
		</dict>
		<key>escaped_characters</key>
		<dict>
			<key>match</key>
			<string>\\(x\h{2}|[0-7]{3}|\n|\"|\'|a|b|f|n|r|t|v|\\)</string>
			<key>name</key>
			<string>constant.character.escaped.special.coconut</string>
		</dict>
		<key>escaped_characters_raw</key>
		<dict>
			<key>match</key>
			<string>\\(\'|")</string>
			<key>name</key>
			<string>constant.character.escaped.raw.special.coconut</string>
		</dict>
		<key>escaped_unicode_characters</key>
		<dict>
			<key>match</key>
			<string>\\(u\h{4}|U\h{8}|N\{[a-zA-Z\s]+\})</string>
			<key>name</key>
			<string>constant.character.escaped.coconut</string>
		</dict>
		<key>f_string_quoted</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([fF])'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][fF]|[fF][rR])'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([fF])'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][fF]|[fF][rR])'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([fF])"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][fF]|[fF][rR])"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([fF])"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][fF]|[fF][rR])"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>format_escape</key>
		<dict>
			<key>match</key>
			<string>({{|}})</string>
			<key>name</key>
			<string>constant.character.escape.fmt.coconut</string>
		</dict>
		<key>format_specifier</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_escape</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>({)(\w*(\.\w+)*)?(!(a|r|s))?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.interpolated.brace.fmt.coconut</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.subscriptor.fmt.coconut</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.exclamation.fmt.coconut</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant.ascii_repr_str.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.interpolated.brace.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.interpolated.format.string.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(:)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.colon.fmt.coconut</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>name</key>
							<string>meta.interpolated.format.specifier.coconut</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#format_specifier_fill_align</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#format_specifier_sign</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#format_specifier_alternate_form</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#format_specifier_zero_padding</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#format_specifier_width</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#format_specifier_thousand_separator</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#format_specifier_precision</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#format_specifier_type</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#format_specifier</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>format_specifier_alternate_form</key>
		<dict>
			<key>begin</key>
			<string>(#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.alternate.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.alternate.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_zero_padding</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_width</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_thousand_separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_precision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_extended</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_escape</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.interpolated.brace.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.interpolated.brace.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.interpolated.format.fstring.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_ascii_repr_str</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_colon</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_fill_align</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_sign</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_alternate_form</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_zero_padding</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_width</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_thousand_separator</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_precision</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_type</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>format_specifier_extended_alternate_form</key>
		<dict>
			<key>begin</key>
			<string>(#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.alternate.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.alternate.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_zero_padding</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_width</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_thousand_separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_precision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_extended_ascii_repr_str</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(!(a|r|s))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.exclamation.fmt.coconut</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.ascii_repr_str.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.ascii_repr_str.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_colon</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_fill_align</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_sign</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_alternate_form</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_zero_padding</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_width</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_thousand_separator</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_precision</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_type</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>format_specifier_extended_colon</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.colon.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.colon.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_fill_align</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_sign</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_alternate_form</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_zero_padding</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_width</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_thousand_separator</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_precision</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended_type</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier_extended</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>format_specifier_extended_fill_align</key>
		<dict>
			<key>begin</key>
			<string>([^{}]?(&lt;|&gt;|=|\^))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.fill_char.fmt.coconut</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.align.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.fill_char.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_sign</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_alternate_form</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_zero_padding</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_width</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_thousand_separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_precision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_extended_precision</key>
		<dict>
			<key>begin</key>
			<string>(\.\d+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.precision.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.precision.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_extended_self</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;={)</string>
					<key>end</key>
					<string>(?=!|:|})</string>
					<key>name</key>
					<string>meta.self.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>format_specifier_extended_sign</key>
		<dict>
			<key>begin</key>
			<string>(\+|-|\s)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.sign.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.sign.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_alternate_form</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_zero_padding</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_width</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_thousand_separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_precision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_extended_thousand_separator</key>
		<dict>
			<key>begin</key>
			<string>(,)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.thousand_separator.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.thousand_separator.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_precision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_extended_type</key>
		<dict>
			<key>begin</key>
			<string>(b|c|d|e|E|f|F|g|G|n|o|s|x|X|%)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.type.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.type.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_extended_width</key>
		<dict>
			<key>begin</key>
			<string>(\d+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.width.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.width.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_thousand_separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_precision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_extended_zero_padding</key>
		<dict>
			<key>begin</key>
			<string>(0)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.zero_padding.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.zero_padding.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_width</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_thousand_separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_precision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_extended</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_fill_align</key>
		<dict>
			<key>begin</key>
			<string>([^{}]?(&lt;|&gt;|=|\^))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.fill_char.fmt.coconut</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.align.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.fill_char.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_sign</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_alternate_form</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_zero_padding</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_width</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_thousand_separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_precision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_precision</key>
		<dict>
			<key>begin</key>
			<string>(\.\d+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.precision.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.precision.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_sign</key>
		<dict>
			<key>begin</key>
			<string>(\+|-|\s)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.sign.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.sign.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_alternate_form</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_zero_padding</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_width</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_thousand_separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_precision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_thousand_separator</key>
		<dict>
			<key>begin</key>
			<string>(,)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.thousand_separator.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.thousand_separator.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_precision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_type</key>
		<dict>
			<key>begin</key>
			<string>(b|c|d|e|E|f|F|g|G|n|o|s|x|X|%)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.type.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.type.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_width</key>
		<dict>
			<key>begin</key>
			<string>(\d+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.width.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.width.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_thousand_separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_precision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier</string>
				</dict>
			</array>
		</dict>
		<key>format_specifier_zero_padding</key>
		<dict>
			<key>begin</key>
			<string>(0)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.zero_padding.fmt.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=})</string>
			<key>name</key>
			<string>meta.zero_padding.fmt.coconut</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format_specifier_width</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_thousand_separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_precision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format_specifier</string>
				</dict>
			</array>
		</dict>
		<key>function_annotation</key>
		<dict>
			<key>begin</key>
			<string>\s*(-&gt;)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.annotation.assignment.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\s*[:=])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>function_arguments</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>(?=\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b([a-zA-Z_]\w*)\s*(?:\([^)]*\)\s*)?(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.coconut</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=[,\n)])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;=(=))\s*</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.coconut</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=[,\n)])</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\s*\b(?=:|\+|\w)</string>
							<key>end</key>
							<string>(?=(=)|[,\n)])</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.coconut</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b([a-zA-Z_]\w*)\s*(?:\([^)]*\)\s*)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=[,\n()])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\s*\b(?=:|\+|\w)</string>
							<key>end</key>
							<string>(?=[,\n)])</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function_entity_name</key>
		<dict>
			<key>begin</key>
			<string>(?=[a-zA-Z_]\w*)</string>
			<key>contentName</key>
			<string>entity.name.function.coconut</string>
			<key>end</key>
			<string>(?!\w)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entity_name_function</string>
				</dict>
			</array>
		</dict>
		<key>generic_names</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z_]\w*</string>
		</dict>
		<key>illegal_names</key>
		<dict>
			<key>match</key>
			<string>\b(and|as|assert|break|class|continue|def|del|elif|else|except|finally|for|from|global|if|import|in|is|lambda|nonlocal|not|or|pass|raise|return|try|while|with|yield|_coconut\w*)\b</string>
			<key>name</key>
			<string>invalid.illegal_names.name.coconut</string>
		</dict>
		<key>keyword_arguments</key>
		<dict>
			<key>begin</key>
			<string>\b([a-zA-Z_]\w*)\s*(=)(?!=)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.coconut</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.coconut</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=[,\n)])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>language_variables</key>
		<dict>
			<key>match</key>
			<string>\b(self|cls)\b</string>
			<key>name</key>
			<string>variable.language.coconut</string>
		</dict>
		<key>magic_function_names</key>
		<dict>
			<key>match</key>
			<string>\b__(abs|add|and|await|bool|bytes|call|ceil|complex|contains|copy|deepcopy|del|delattr|delete|delitem|dir|div|divmod|a?enter|eq|a?exit|float|floor|floordiv|format|ge|get|getattr|getattribute|getinitargs|getitem|getnewargs|getstate|gt|hash|hex|iadd|iand|idiv|ifloordiv|ilshift|imul|index|init|instancecheck|int|invert|ior|ipow|irshift|isub|a?iter|itruediv|ixor|le|len|lshift|lt|metaclass|missing|mod|mul|ne|neg|new|a?next|oct|or|pos|pow|prepare|radd|rand|rdiv|rdivmod|reduce|reduce_ex|repr|reversed|rfloordiv|rlshift|rmod|rmul|ror|round|rpow|rrshift|rshift|rsub|rtruediv|rxor|set|setattr|setitem|setstate|sizeof|str|sub|subclasscheck|subclasshook|truediv|trunc|unicode|weakref|xor|fmap)__\b</string>
			<key>name</key>
			<string>support.function.magic.coconut</string>
		</dict>
		<key>magic_variable_names</key>
		<dict>
			<key>match</key>
			<string>\b__(all|annotations|bases|builtins|class|debug|dict|doc|file|members|metaclass|mro|name|qualname|slots|weakref)__\b</string>
			<key>name</key>
			<string>support.variable.magic.coconut</string>
		</dict>
		<key>regular_expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\()\?(=|!|&lt;=|&lt;!|:|P&lt;[a-zA-Z_]\w*?&gt;|\(([1-9]\d?|[a-zA-Z_]\w*)\))</string>
					<key>name</key>
					<string>constant.character.escape.coconut</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.coconut</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\((\?P=)([a-zA-Z_]\w*)\)</string>
					<key>name</key>
					<string>keyword.other.group_reference_name.regex.coconut</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.coconut</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\g)&lt;([a-zA-Z_]\w*|[1-9]\d*)&gt;</string>
					<key>name</key>
					<string>keyword.other.group_reference_name.regex.coconut</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[bBAZzG]|\^|\$</string>
					<key>name</key>
					<string>keyword.control.anchor.regex.coconut</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[1-9]\d*</string>
					<key>name</key>
					<string>keyword.other.group_reference_order.regex.coconut</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[?+*][?+]?|\{(\d+,\d+|\d+,|,\d+|\d+)\}\??</string>
					<key>name</key>
					<string>keyword.operator.quantifier.regex.coconut</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>keyword.operator.or.regex.coconut</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(\?#</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>comment.block.regex.coconut</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\(\?[aiLmsux]+\)</string>
					<key>name</key>
					<string>keyword.other.option_toggle.regex.coconut</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regular_expressions_escaped_characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regular_expressions_character_classes</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[()]</string>
					<key>name</key>
					<string>keyword.operator.group.regex.coconut</string>
				</dict>
			</array>
		</dict>
		<key>regular_expressions_character_classes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[wWsSdD]|\.</string>
					<key>name</key>
					<string>constant.character.character_class.regex.coconut</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[(\^)?(\](?=.*\]))?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.negation.regex.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>constant.other.character_class.set.regex.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\[|\\\\|\\\]</string>
							<key>name</key>
							<string>constant.character.escaped.special.regex.except.coconut</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions_character_classes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions_escaped_characters</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>regular_expressions_escaped_characters</key>
		<dict>
			<key>match</key>
			<string>\\(\\|\?|\.|\*|\+|\{|\}|\||\(|\)|\[|\]|\^|\$)</string>
			<key>name</key>
			<string>constant.character.escaped.special.regex.coconut</string>
		</dict>
		<key>string_patterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped_unicode_characters</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([bBuU]?)'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([bBuU]?)'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([bBuU]?)"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([bBuU]?)"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string_quoted_format</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([uUbB]?)'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([uUbB]?)'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([uUbB]?)"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([uUbB]?)"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#format_specifier</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string_quoted_old</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([uUbB]?)'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant_placeholder</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant_placeholder</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([uUbB]?)'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant_placeholder</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant_placeholder</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([uUbB]?)"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant_placeholder</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant_placeholder</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([uUbB]?)"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant_placeholder</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant_placeholder</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string_quoted_regex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.re.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.re.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.re.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.re.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.re.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.re.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.re.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.re.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.re.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.re.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string_quoted_template</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([uUbB]?)'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#template_string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#template_string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([uUbB]?)'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#template_string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#template_string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([uUbB]?)"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#template_string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#template_string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([uUbB]?)"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#template_string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]?|[bB][rR])"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.fmt.coconut</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.fmt.coconut</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.fmt.coconut</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_characters_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#template_string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>template_string</key>
		<dict>
			<key>match</key>
			<string>\$(\$|[a-zA-Z_]\w*|{[a-zA-Z_]\w*})</string>
			<key>name</key>
			<string>string.interpolated.template.coconut</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.coconut</string>
	<key>uuid</key>
	<string>7da2bcb1-621d-43b0-a187-c42d158b22ed</string>
</dict>
</plist>
